### ISSUE TITLE
Eyetribe Calibration

### ISSUE THREAD

**Issue by jespa007** [EyeTribe/tet-cpp-client#5]
Hi there,

I have used Eyetribe for some time ago and always I had problems during the calibration. The problem is that some times I don't receive the end point or start point message (so maybe is hanged) directly using json messages that Eyetribe specifies at his website. So I thought I had something wrong with my code and I decided use your API to have better luck but I didn't have. Despite the calibration using your C Api doesn't hang is difficult to have a calibration result. So my question is, Is there something wrong within eyetribe software ?

Regards

**Comment by arnebp** [comment]
We have verified this bug. It will be addressed in our next release. This release should happen before May 16th.

Thx for your feedback.

**Comment by arnebp** [comment]
The update has been released and should fix this issue.

**Comment by jespa007** [comment]
Sorry for my late response and thanks arnebp :). I'll check the new release when I have time.
